### ISSUE TITLE
Указанная гарантия не соответсвуют реализации

### ISSUE THREAD

**Issue by simplydesigner** [rexxh/S.T.A.C.K.#2]
- [x] [push](https://github.com/rexxh/S.T.A.C.K./blob/6207976a4601e92d36c9dda2ddcda835792ecc24/include/Stack.hpp#L64-L82)
- [x] [operator =](https://github.com/rexxh/S.T.A.C.K./blob/d38e2fd28d2f811006a9a6680f09d24d6a5ad6a3/include/Stack.hpp#L78-L85)
- [x] [New_n_copy](https://github.com/rexxh/S.T.A.C.K./blob/d38e2fd28d2f811006a9a6680f09d24d6a5ad6a3/include/Stack.hpp#L103-L108)

**Comment by rexxh** [comment]
Исправил
